### ISSUE TITLE
Move examples into main steppy

### ISSUE THREAD

**Issue by stared** [minerva-ml/steppy-examples#5]
For de facto tutorial, wouldn't it be better to have this tutorial inside the main repo? It's would be way easier to discover that, and make sure that they have the same version as steppy.

And, if needed, have separate repo(s) for more bulky examples.

**Comment by kamil-kaczmarek** [comment]
Hi @stared our intention behind making separate repo was to keep `steppy` containing only necessary files. We intentionally, didn't want to put any notebooks there. Thank to this PyPI package does not contain notebooks.

**Comment by stared** [comment]
@kamil-kaczmarek I understand (and are well aware of that), but disagree. 

Of course, putting notebooks is "dirty". But with a small project size, it is (IMHO) a good tradeoff - readily visible materials, from the same version etc. Sure, for big projects (dozens of active contributors, thousands of commits) there is often a separate repo for docs, etc.   

(Though, I understand it is a controversial point.)

**Comment by kamil-kaczmarek** [comment]
Hi @stared, I see you point.

You are clearly right that for small projects like `steppy` it is beneficial to have tutorials in one place. However, my argument holds true as well.

Let me just reconsider this again. Processing...
:smiley: 

Thanks for your feedback!

Best,
Kamil
